"""empty message

Revision ID: 411ab705a015
Revises: 
Create Date: 2022-08-12 19:04:22.610062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411ab705a015'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('profile_pic', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chirps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(length=2000), nullable=True),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media', sa.String(length=2000), nullable=True),
    sa.Column('body', sa.String(length=300), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('chirpId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chirpId'], ['chirps.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likes',
    sa.Column('users', sa.Integer(), nullable=False),
    sa.Column('chirps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chirps'], ['chirps.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users', 'chirps')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    op.drop_table('comments')
    op.drop_table('chirps')
    op.drop_table('users')
    # ### end Alembic commands ###
